on:
  push:
    paths:
      - 'Astor.Logging/**'
      - '.github/workflows/nuget.yaml'
  workflow_dispatch:
    
jobs:
  publish:
    name: Pack & Publish nuget
    runs-on: ubuntu-latest
    steps:
      - uses: astorDev/versy/calver/nuget@main
        with:
          project: Astor.Logging/Astor.Logging
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}